---
title: "Visualization part III exploratory analysis"
author: "hanfu shi"
date: "2021/10/12"
output: html_document
editor_options: 
  chunk_output_type: console
---
##Setting options
```{r }
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d


```

#load the weather data
```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31"  )%>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

```


## `group_by`
```{r}
weather_df%>%
  group_by(name, month)

```


##counting things
count month/name observations
```{r}
weather_df %>%
  group_by(name,month)%>%
  summarize(n_obs = n())

```


we can use `count()`
```{r}
weather_df%>%
 count(month, name, name="n_obs")

```

**NEVER** use base R's `table`
```{r}
weather_df%>%
  pull(month)%>%
  table()

```

other helpful counters
```{r}

weather_df %>%
  group_by(month)%>%
  summarize(
    n_obs=n(),
    n_days = n_distinct(date)
  )
  
```


## A digression on 2x2table
```{r}
weather_df %>%
  filter(name != "Waikiki_HA")%>%
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE ~ ""
    )
  )%>%
  group_by(name,cold)%>%
  summarize(count = n())
 


```

#another way to make 2x2 table
```{r}
weather_df %>%
  filter(name != "Waikiki_HA")%>%
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE ~ ""
    )
  )%>%
  janitor::tabyl(name,cold)
```


```{r}



```



```{r}



```








