---
title: "Visualization part II"
author: "hanfu shi"
date: "2021/10/7"
output: html_document
---
```{r}
library(tidyverse)
library(patchwork)

```

load weather data


```{r }
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

remember this plot..?
```{r}
weather_df%>%
  ggplot(aes(x = tmin, y=tmax, color = name))+
  geom_point(alpha = 0.5)


```


labels

```{r}
weather_df%>%
  ggplot(aes(x = tmin, y=tmax, color = name))+
  geom_point(alpha = 0.5)+
  labs(title = "Temperature plot",
       x =  "minimum daily temperature",
       y = "Maximum daily temperature(c)",
       caption = "Data from rnooo package; temperature in 2017.")


```


## Scales

Start with the same plot
```{r}
weather_df%>%
  ggplot(aes(x = tmin, y=tmax, color = name))+
  geom_point(alpha = 0.5)+
  labs(title = "Temperature plot",
       x =  "minimum daily temperature",
       y = "Maximum daily temperature(c)",
       caption = "Data from rnooo package; temperature in 2017.")+
  scale_x_continuous(
    breaks = c(-15, 0 ,15),
    labels = c("-15C","0","15")
  )+
  scale_y_continuous(
   # trans = "sqrt",  or "log"
    position = "right" #change lable side
  )


```


look at color scales
```{r}
weather_df%>%
  ggplot(aes(x = tmin, y=tmax, color = name))+
  geom_point(alpha = 0.5)+
  labs(title = "Temperature plot",
       x =  "minimum daily temperature",
       y = "Maximum daily temperature(c)",
       caption = "Data from rnooo package; temperature in 2017.")+
  scale_x_continuous(
    breaks = c(-15, 0 ,15),
    labels = c("-15C","0","15")
  )+
  scale_color_hue(
    h = c(100, 300), 
    name = "Location"
    )#change name of label

```

```{r}
weather_df%>%
  ggplot(aes(x = tmin, y=tmax, color = name))+
  geom_point(alpha = 0.7)+
  labs(title = "Temperature plot",
       x =  "minimum daily temperature",
       y = "Maximum daily temperature(c)",
       caption = "Data from rnooo package; temperature in 2017.")+
  scale_x_continuous(
    breaks = c(-15, 0 ,15),
    labels = c("-15C","0","15"))+
  
  viridis::scale_color_viridis(
    name ="locations",
    discrete = T
  )
#use viridis
```


## Themes
shift the legend
```{r}
weather_df%>%
  ggplot(aes(x = tmin, y=tmax, color = name))+
  geom_point(alpha = 0.5)+
  labs(title = "Temperature plot",
       x =  "minimum daily temperature",
       y = "Maximum daily temperature(c)",
       caption = "Data from rnooo package; temperature in 2017.")+
  scale_x_continuous(
    breaks = c(-15, 0 ,15),
    labels = c("-15C","0","15"))+
  
  viridis::scale_color_viridis(
    name ="locations",
    discrete = T
  )+
  theme(legend.position = "bottom")

```

change the overall theme
```{r}
weather_df%>%
  ggplot(aes(x = tmin, y=tmax, color = name))+
  geom_point(alpha = 0.5)+
  labs(title = "Temperature plot",
       x =  "minimum daily temperature",
       y = "Maximum daily temperature(c)",
       caption = "Data from rnooo package; temperature in 2017.")+
  scale_x_continuous(
    breaks = c(-15, 0 ,15),
    labels = c("-15C","0","15"))+
  
  viridis::scale_color_viridis(
    name ="locations",
    discrete = T
  )+
  theme(legend.position = "bottom",)+
  theme_minimal()

```
